/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pack */
        post: operations["pack_api_pack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/single-layer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Single Layer
         * @description Compute optimal layout for exactly one layer of a given box type.
         *
         *     Used by the Layer Builder mode where the user assembles the pallet
         *     one layer at a time. For 50r types, returns the cross-kontovka pattern
         *     (flat + right strip + back strip). For others, returns the best pure
         *     flat grid.
         */
        post: operations["single_layer_api_single_layer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Xlsx */
        post: operations["import_xlsx_api_import_xlsx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auftraege": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Auftraege
         * @description Queue (status=queued) plus my own in_progress, in queue order.
         *
         *     Returns Detail (incl. parsed JSONB) — frontend list cards need
         *     pallet/article counts and meta.sendungsnummer from parsed.
         */
        get: operations["list_auftraege_api_auftraege_get"];
        put?: never;
        /** Create Auftrag */
        post: operations["create_auftrag_api_auftraege_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auftraege/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reorder Queue
         * @description Bulk update queue_position; only affects status=queued rows.
         */
        patch: operations["reorder_queue_api_auftraege_reorder_patch"];
        trace?: never;
    };
    "/api/auftraege/{auftrag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auftrag */
        get: operations["get_auftrag_api_auftraege__auftrag_id__get"];
        put?: never;
        post?: never;
        /** Delete Auftrag */
        delete: operations["delete_auftrag_api_auftraege__auftrag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auftraege/{auftrag_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Auftrag
         * @description Atomic claim: succeeds only if status was 'queued' AND the caller
         *     has no other in_progress Auftrag. One active task per user — without
         *     this guard the frontend's currentSrc=.find(...) hides extras.
         */
        post: operations["start_auftrag_api_auftraege__auftrag_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auftraege/{auftrag_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Progress */
        patch: operations["update_progress_api_auftraege__auftrag_id__progress_patch"];
        trace?: never;
    };
    "/api/auftraege/{auftrag_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Auftrag */
        post: operations["complete_auftrag_api_auftraege__auftrag_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auftraege/{auftrag_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Auftrag
         * @description Release in_progress Auftrag back to the queue.
         */
        post: operations["cancel_auftrag_api_auftraege__auftrag_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List History
         * @description All completed Auftrag, newest first. Paginated.
         */
        get: operations["list_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{auftrag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete History Entry */
        delete: operations["delete_history_entry_api_history__auftrag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Ping */
        get: operations["admin_ping_api_admin_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auftraege": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Auftraege */
        get: operations["admin_list_auftraege_api_admin_auftraege_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Users */
        get: operations["admin_list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Change User Role */
        patch: operations["admin_change_user_role_api_admin_users__user_id__role_patch"];
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Audit */
        get: operations["admin_list_audit_api_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Stats */
        get: operations["admin_stats_api_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sku-dimensions/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup Sku Dimensions
         * @description Batch lookup for FNSKU/SKU/EAN. Returns one entry per matched key.
         *
         *     The same row can be reachable through multiple keys (multiple
         *     FNSKUs / SKUs / EANs in their respective arrays), so callers can
         *     probe with whichever identifier they have. Each requested key that
         *     hits gets bound under itself in the response.
         */
        get: operations["lookup_sku_dimensions_api_sku_dimensions_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sku-dimensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Sku Dimensions */
        get: operations["admin_list_sku_dimensions_api_admin_sku_dimensions_get"];
        put?: never;
        /** Admin Create Sku Dimension */
        post: operations["admin_create_sku_dimension_api_admin_sku_dimensions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sku-dimensions/{row_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin Delete Sku Dimension */
        delete: operations["admin_delete_sku_dimension_api_admin_sku_dimensions__row_id__delete"];
        options?: never;
        head?: never;
        /** Admin Update Sku Dimension */
        patch: operations["admin_update_sku_dimension_api_admin_sku_dimensions__row_id__patch"];
        trace?: never;
    };
    "/api/admin/sku-dimensions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Import Sku Dimensions
         * @description Upload Dimensional_list.xlsx. The same physical product often
         *     ships under several FNSKUs/SKUs (PRIME vs EV vs regional channel),
         *     so this importer DEDUPES: any incoming row that shares ANY key
         *     (FNSKU / SKU / EAN) with an existing row is merged into it — the
         *     keys accumulate, dimensions get refreshed.
         *
         *     Required columns (case-insensitive, alias-tolerant):
         *       FNSKU | SKU | EAN | Title | L (cm) | B (cm) | H (cm) | Gewicht (kg)
         */
        post: operations["admin_import_sku_dimensions_api_admin_sku_dimensions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sku-dimensions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Export Sku Dimensions */
        get: operations["admin_export_sku_dimensions_api_admin_sku_dimensions_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Auftraege */
        get: operations["search_auftraege_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_activity_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/shift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Shift
         * @description Working-day window for the calling user.
         *
         *     `started_at` = first audit_log row whose UTC timestamp falls on
         *     today's UTC date for this user. Cheap because of the existing
         *     `idx_audit_user_created` (user_id, created_at) index.
         *
         *     `completed_today` is a separate count over auftraege.finished_at —
         *     audit rows with action='complete' would also work but the dedicated
         *     column reads cleaner and is consistent with /api/admin/stats.
         */
        get: operations["my_shift_api_activity_shift_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/auftraege.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Auftraege */
        get: operations["export_auftraege_api_exports_auftraege_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Lightweight readiness probe — no DB hit. Used by Railway's
         *     health check; returns 200 as long as the process is alive. For a
         *     real diagnostic that checks DB connectivity, call /api/health.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Health
         * @description Diagnostic endpoint with DB ping + uptime + version. Pings the
         *     DB with a trivial SELECT 1 so a hung Postgres surfaces here even
         *     when the FastAPI process itself is fine. The DynamicIsland's
         *     connection probe + any external monitor can call this every 30s.
         */
        get: operations["api_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spa Fallback */
        get: operations["spa_fallback__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActiveWorker
         * @description Operator who currently has an in_progress Auftrag.
         */
        ActiveWorker: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** User Name */
            user_name: string;
            /**
             * Auftrag Id
             * Format: uuid
             */
            auftrag_id: string;
            /** File Name */
            file_name: string;
            /** Fba Code */
            fba_code?: string | null;
            step?: components["schemas"]["WorkflowStep"] | null;
            /** Started At */
            started_at?: string | null;
            /** Current Pallet Idx */
            current_pallet_idx?: number | null;
            /**
             * Pallet Count
             * @default 0
             */
            pallet_count: number;
        };
        /**
         * ActivityEvent
         * @description One audit_log row, joined with user + (optional) Auftrag file name.
         */
        ActivityEvent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Action */
            action: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** User Name */
            user_name?: string | null;
            /** Auftrag Id */
            auftrag_id?: string | null;
            /** Auftrag File Name */
            auftrag_file_name?: string | null;
            /** Fba Code */
            fba_code?: string | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** ActivityFeed */
        ActivityFeed: {
            /** Active Workers */
            active_workers?: components["schemas"]["ActiveWorker"][];
            /** Events */
            events?: components["schemas"]["ActivityEvent"][];
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** AdminStats */
        AdminStats: {
            /** Total Auftraege */
            total_auftraege: number;
            /** Queued Now */
            queued_now: number;
            /** In Progress Now */
            in_progress_now: number;
            /** Completed Total */
            completed_total: number;
            /** Completed Today */
            completed_today: number;
            /** Completed This Week */
            completed_this_week: number;
            /** Avg Duration Sec */
            avg_duration_sec?: number | null;
            /** Top Users */
            top_users?: {
                [key: string]: unknown;
            }[];
            /** Completed Per Day */
            completed_per_day?: {
                [key: string]: unknown;
            }[];
        };
        /** AdminUserDetail */
        AdminUserDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Clerk Id */
            clerk_id?: string | null;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at?: string | null;
            /**
             * Auftraege Completed
             * @default 0
             */
            auftraege_completed: number;
        };
        /** AuditLogEntry */
        AuditLogEntry: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Action */
            action: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** User Name */
            user_name?: string | null;
            /** Auftrag Id */
            auftrag_id?: string | null;
            /** Auftrag File Name */
            auftrag_file_name?: string | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /**
         * AuftragCreate
         * @description POST /api/auftraege — frontend already parsed the .docx in browser.
         */
        AuftragCreate: {
            /** File Name */
            file_name: string;
            /** Raw Text */
            raw_text?: string | null;
            /** Parsed */
            parsed?: {
                [key: string]: unknown;
            } | null;
            /** Validation */
            validation?: {
                [key: string]: unknown;
            } | null;
            /** Error Message */
            error_message?: string | null;
        };
        /**
         * AuftragDetail
         * @description Full record incl. parsed payload, raw text, and workflow state.
         */
        AuftragDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** File Name */
            file_name: string;
            /** Fba Code */
            fba_code?: string | null;
            status: components["schemas"]["AuftragStatus"];
            /**
             * Pallet Count
             * @default 0
             */
            pallet_count: number;
            /**
             * Article Count
             * @default 0
             */
            article_count: number;
            /** Error Message */
            error_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Queue Position */
            queue_position?: number | null;
            /** Assigned To User Id */
            assigned_to_user_id?: string | null;
            /** Assigned To User Name */
            assigned_to_user_name?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Pallet Timings */
            pallet_timings?: {
                [key: string]: unknown;
            };
            /** Raw Text */
            raw_text?: string | null;
            /** Parsed */
            parsed?: {
                [key: string]: unknown;
            } | null;
            /** Validation */
            validation?: {
                [key: string]: unknown;
            } | null;
            step?: components["schemas"]["WorkflowStep"] | null;
            /** Current Pallet Idx */
            current_pallet_idx?: number | null;
            /** Current Item Idx */
            current_item_idx?: number | null;
            /** Completed Keys */
            completed_keys?: {
                [key: string]: unknown;
            };
        };
        /**
         * AuftragReorderItem
         * @description One row of PATCH /api/auftraege/reorder body.
         */
        AuftragReorderItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Queue Position */
            queue_position: number;
        };
        /**
         * AuftragStatus
         * @enum {string}
         */
        AuftragStatus: "queued" | "in_progress" | "completed" | "error";
        /**
         * AuftragSummary
         * @description Compact row for list views (queue + history). No JSONB blobs.
         */
        AuftragSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** File Name */
            file_name: string;
            /** Fba Code */
            fba_code?: string | null;
            status: components["schemas"]["AuftragStatus"];
            /**
             * Pallet Count
             * @default 0
             */
            pallet_count: number;
            /**
             * Article Count
             * @default 0
             */
            article_count: number;
            /** Error Message */
            error_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Queue Position */
            queue_position?: number | null;
            /** Assigned To User Id */
            assigned_to_user_id?: string | null;
            /** Assigned To User Name */
            assigned_to_user_name?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Pallet Timings */
            pallet_timings?: {
                [key: string]: unknown;
            };
        };
        /** Body_admin_import_sku_dimensions_api_admin_sku_dimensions_import_post */
        Body_admin_import_sku_dimensions_api_admin_sku_dimensions_import_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_import_xlsx_api_import_xlsx_post */
        Body_import_xlsx_api_import_xlsx_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** BoxInput */
        BoxInput: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Length */
            length: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Quantity */
            quantity: number;
            /**
             * Color
             * @default #888888
             */
            color: string;
            /**
             * Allowed Orientations
             * @default [
             *       "flat",
             *       "stand"
             *     ]
             */
            allowed_orientations: ("flat" | "stand")[];
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /**
         * FixedObstacle
         * @description A locked region of the pallet — boxes already physically placed.
         *     The packer treats these as immovable: new boxes cannot overlap, but
         *     can rest ON TOP of them (they count as supporters).
         */
        FixedObstacle: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** L */
            l: number;
            /** W */
            w: number;
            /** H */
            h: number;
            /** Type Id */
            type_id?: string | null;
        };
        /**
         * ForcedGrid
         * @description Override the natural packing grid for a specific box type.
         */
        ForcedGrid: {
            /** Cols */
            cols: number;
            /** Rows */
            rows: number;
            /** Box L */
            box_l: number;
            /** Box W */
            box_w: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryPage
         * @description Paginated history response.
         */
        HistoryPage: {
            /** Items */
            items: components["schemas"]["AuftragSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ImportResponse */
        ImportResponse: {
            /** Boxes Found */
            boxes_found: number;
            /** Boxes */
            boxes: components["schemas"]["ImportedBox"][];
            /** Warnings */
            warnings: string[];
        };
        /** ImportedBox */
        ImportedBox: {
            /** Name */
            name: string;
            /** Length */
            length: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Max Per Pallet */
            max_per_pallet?: number | null;
        };
        /** LayerDescription */
        LayerDescription: {
            /** Headline */
            headline: string;
            /** Body */
            body: string;
            /**
             * Zones
             * @default []
             */
            zones: components["schemas"]["ZoneDesc"][];
        };
        /** LayerRecord */
        LayerRecord: {
            /** Index */
            index: number;
            /** Z Bottom */
            z_bottom: number;
            /** Z Top */
            z_top: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pure" | "half-split" | "tri-split" | "mixed-edge" | "center-cap";
            /** Type Breakdown */
            type_breakdown: {
                [key: string]: number;
            };
            description: components["schemas"]["LayerDescription"];
            /** Count */
            count: number;
        };
        /** Orientation */
        Orientation: {
            /** L */
            l: number;
            /** W */
            w: number;
            /** H */
            h: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "flat" | "stand";
        };
        /** PackOptions */
        PackOptions: {
            /**
             * Overhang Pct
             * @default 0
             */
            overhang_pct: number;
            /**
             * Max Kontovka Columns
             * @default 3
             */
            max_kontovka_columns: number;
            /**
             * Zones
             * @default []
             */
            zones: components["schemas"]["ZoneDefinition"][];
            /**
             * Preferred Mode
             * @default auto
             * @enum {string}
             */
            preferred_mode: "auto" | "guillotine" | "layered" | "cpsat";
            /** Forced Grids */
            forced_grids?: {
                [key: string]: components["schemas"]["ForcedGrid"];
            } | null;
            /**
             * Cpsat Time Limit S
             * @default 30
             */
            cpsat_time_limit_s: number;
            /**
             * Fixed Obstacles
             * @default []
             */
            fixed_obstacles: components["schemas"]["FixedObstacle"][];
        };
        /** PackRequest */
        PackRequest: {
            /** Boxes */
            boxes: components["schemas"]["BoxInput"][];
            pallet?: components["schemas"]["PalletConfig"];
            options?: components["schemas"]["PackOptions"];
        };
        /** PackResponse */
        PackResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "column-hybrid" | "layered";
            /** Placed Boxes */
            placed_boxes: components["schemas"]["PlacedBox"][];
            /** Layers */
            layers: components["schemas"]["LayerRecord"][];
            /** Zones */
            zones: components["schemas"]["ZoneResult"][];
            stats: components["schemas"]["PackStats"];
        };
        /** PackStats */
        PackStats: {
            /** Total Boxes */
            total_boxes: number;
            /** Requested */
            requested: number;
            /** Layer Count */
            layer_count: number;
            /** Total Height */
            total_height: number;
            /** Fill Pct */
            fill_pct: number;
            /** Efficiency */
            efficiency: number;
            /** Unplaced */
            unplaced: {
                [key: string]: number;
            };
            /** Mode */
            mode: string;
        };
        /** Paginated[AuditLogEntry] */
        Paginated_AuditLogEntry_: {
            /** Items */
            items: components["schemas"]["AuditLogEntry"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Paginated[AuftragSummary] */
        Paginated_AuftragSummary_: {
            /** Items */
            items: components["schemas"]["AuftragSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Paginated[SkuDimensionRead] */
        Paginated_SkuDimensionRead_: {
            /** Items */
            items: components["schemas"]["SkuDimensionRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PalletConfig */
        PalletConfig: {
            /**
             * Length
             * @default 120
             */
            length: number;
            /**
             * Width
             * @default 80
             */
            width: number;
            /**
             * Pallet Height
             * @default 14.4
             */
            pallet_height: number;
            /**
             * Max Total Height
             * @default 180
             */
            max_total_height: number;
        };
        /** PlacedBox */
        PlacedBox: {
            /** Id */
            id: string;
            /** Type Id */
            type_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** L */
            l: number;
            /** W */
            w: number;
            /** H */
            h: number;
            /**
             * Ori Kind
             * @enum {string}
             */
            ori_kind: "flat" | "stand";
            /** Layer Index */
            layer_index: number;
            /** Zone Id */
            zone_id?: string | null;
            /**
             * Support Fraction
             * @default 1
             */
            support_fraction: number;
        };
        /** RoleUpdate */
        RoleUpdate: {
            role: components["schemas"]["UserRole"];
        };
        /**
         * SearchHit
         * @description One row in /api/search results.
         *
         *     `matched_field` and `matched_value` describe WHERE the query hit so
         *     the UI can highlight context. Computed in Python after the SQL pull
         *     because PostgreSQL ILIKE %query% returns rows but doesn't tell you
         *     which field of the JSONB matched.
         */
        SearchHit: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** File Name */
            file_name: string;
            /** Fba Code */
            fba_code?: string | null;
            status: components["schemas"]["AuftragStatus"];
            /**
             * Pallet Count
             * @default 0
             */
            pallet_count: number;
            /**
             * Article Count
             * @default 0
             */
            article_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Assigned To User Name */
            assigned_to_user_name?: string | null;
            /** Matched Field */
            matched_field?: string | null;
            /** Matched Value */
            matched_value?: string | null;
        };
        /** SearchResults */
        SearchResults: {
            /** Items */
            items: components["schemas"]["SearchHit"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Query */
            query: string;
        };
        /**
         * ShiftInfo
         * @description Working-day window for a single user, derived from audit_log.
         *
         *     started_at is the first audit row of the local calendar day for that
         *     user; null means the operator hasn't done anything today yet.
         */
        ShiftInfo: {
            /** Started At */
            started_at?: string | null;
            /**
             * Duration Sec
             * @default 0
             */
            duration_sec: number;
            /**
             * Completed Today
             * @default 0
             */
            completed_today: number;
        };
        /**
         * SingleLayerBox
         * @description Minimal box spec for single-layer endpoint.
         */
        SingleLayerBox: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Length */
            length: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Allowed Orientations
             * @default [
             *       "flat",
             *       "stand"
             *     ]
             */
            allowed_orientations: ("flat" | "stand")[];
        };
        /** SingleLayerRequest */
        SingleLayerRequest: {
            box: components["schemas"]["SingleLayerBox"];
            pallet?: components["schemas"]["PalletConfig"];
            /**
             * Current Z
             * @default 0
             */
            current_z: number;
            /**
             * Max Kontovka
             * @default 3
             */
            max_kontovka: number;
            /**
             * Overhang Pct
             * @default 0.05
             */
            overhang_pct: number;
        };
        /** SingleLayerResponse */
        SingleLayerResponse: {
            /** Positions */
            positions: components["schemas"]["PlacedBox"][];
            /** Layer H */
            layer_h: number;
            /** Count */
            count: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pure" | "mixed-edge";
            /** Headline */
            headline: string;
            /**
             * Flat Count
             * @default 0
             */
            flat_count: number;
            /**
             * Stand Count
             * @default 0
             */
            stand_count: number;
        };
        /** SkuDimensionImportResult */
        SkuDimensionImportResult: {
            /**
             * Imported
             * @default 0
             */
            imported: number;
            /**
             * Updated
             * @default 0
             */
            updated: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * SkuDimensionLookup
         * @description Compact form embedded in the lookup response. Includes the row's
         *     `id` (so the distributor can group same-format items even when they
         *     share dims but ship under different SKUs) and `pallet_load_max` (the
         *     empirical capacity used by the normalised-fraction algorithm).
         */
        SkuDimensionLookup: {
            /** Id */
            id: number;
            /** Length Cm */
            length_cm: number;
            /** Width Cm */
            width_cm: number;
            /** Height Cm */
            height_cm: number;
            /** Weight Kg */
            weight_kg: number;
            /** Pallet Load Max */
            pallet_load_max?: number | null;
            /** Source */
            source?: string | null;
        };
        /**
         * SkuDimensionLookupResponse
         * @description Batch lookup result: { lookups: { "<key>": dim, ... }, missing: [...] }.
         *
         *     A single physical-product row can be reachable through several keys —
         *     the response binds the SAME compact dim under each requested key
         *     that hit it. So callers can probe with whichever identifier they
         *     have and always get back the dimensions.
         */
        SkuDimensionLookupResponse: {
            /** Lookups */
            lookups?: {
                [key: string]: components["schemas"]["SkuDimensionLookup"];
            };
            /** Missing */
            missing?: string[];
        };
        /**
         * SkuDimensionRead
         * @description Row as returned to admin/list and to lookup callers.
         *
         *     Each key type is a list because one physical product (one row) often
         *     ships under multiple Amazon FNSKUs / merchant SKUs (different
         *     sales channels, regions, PRIME vs EV).
         */
        SkuDimensionRead: {
            /** Id */
            id: number;
            /** Fnskus */
            fnskus?: string[];
            /** Skus */
            skus?: string[];
            /** Eans */
            eans?: string[];
            /** Title */
            title?: string | null;
            /** Length Cm */
            length_cm: number;
            /** Width Cm */
            width_cm: number;
            /** Height Cm */
            height_cm: number;
            /** Weight Kg */
            weight_kg: number;
            /** Pallet Load Max */
            pallet_load_max?: number | null;
            /** Source */
            source?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by?: string | null;
        };
        /**
         * SkuDimensionUpsert
         * @description POST/PATCH input. At least one of (fnskus, skus, eans) must be non-empty.
         *
         *     Dimensions must be > 0 (a row without size is meaningless for the
         *     distributor). Weight may be 0 as a "not measured yet" placeholder —
         *     edit later via UI when the scale data arrives. `pallet_load_max` is
         *     optional; when null the distributor falls back to the volume soft
         *     limit (1.59 m³).
         */
        SkuDimensionUpsert: {
            /** Fnskus */
            fnskus?: string[];
            /** Skus */
            skus?: string[];
            /** Eans */
            eans?: string[];
            /** Title */
            title?: string | null;
            /** Length Cm */
            length_cm: number;
            /** Width Cm */
            width_cm: number;
            /** Height Cm */
            height_cm: number;
            /** Weight Kg */
            weight_kg: number;
            /** Pallet Load Max */
            pallet_load_max?: number | null;
        };
        /**
         * UserListItem
         * @description Compact form for the GET /api/users dropdown — no email/role.
         */
        UserListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "user";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowProgress
         * @description PATCH /api/auftraege/{id}/progress — only fields actually being updated.
         */
        WorkflowProgress: {
            step?: components["schemas"]["WorkflowStep"] | null;
            /** Current Pallet Idx */
            current_pallet_idx?: number | null;
            /** Current Item Idx */
            current_item_idx?: number | null;
            /** Completed Keys */
            completed_keys?: {
                [key: string]: unknown;
            } | null;
            /** Pallet Timings */
            pallet_timings?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * WorkflowStep
         * @enum {string}
         */
        WorkflowStep: "upload" | "pruefen" | "focus" | "abschluss";
        /** ZoneDefinition */
        ZoneDefinition: {
            /** Id */
            id: string;
            /** Rect */
            rect: {
                [key: string]: number;
            };
            /** Box Ids */
            box_ids: string[];
        };
        /** ZoneDesc */
        ZoneDesc: {
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** ZoneResult */
        ZoneResult: {
            /** Id */
            id: string;
            /** Rect */
            rect: {
                [key: string]: number;
            };
            /** Type Id */
            type_id: string;
            orientation: components["schemas"]["Orientation"];
            /** Grid */
            grid: {
                [key: string]: number;
            };
            /** Tiers */
            tiers: number;
            /** Boxes */
            boxes: number;
            /** Z Top */
            z_top: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    pack_api_pack_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    single_layer_api_single_layer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SingleLayerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleLayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_xlsx_api_import_xlsx_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_xlsx_api_import_xlsx_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_auftraege_api_auftraege_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuftragDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_auftrag_api_auftraege_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuftragCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuftragDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_queue_api_auftraege_reorder_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuftragReorderItem"][];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auftrag_api_auftraege__auftrag_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                auftrag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuftragDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_auftrag_api_auftraege__auftrag_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                auftrag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_auftrag_api_auftraege__auftrag_id__start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                auftrag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuftragDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_progress_api_auftraege__auftrag_id__progress_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                auftrag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowProgress"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuftragDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_auftrag_api_auftraege__auftrag_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                auftrag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuftragDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_auftrag_api_auftraege__auftrag_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                auftrag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuftragDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItem"][];
                };
            };
        };
    };
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_api_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_history_entry_api_history__auftrag_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                auftrag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_ping_api_admin_ping_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_auftraege_api_admin_auftraege_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["AuftragStatus"] | null;
                assigned_to?: string | null;
                /** @description case-insensitive match on file_name */
                search?: string | null;
                sort_by?: string;
                sort_dir?: string;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paginated_AuftragSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_change_user_role_api_admin_users__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_audit_api_admin_audit_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                action?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paginated_AuditLogEntry_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_stats_api_admin_stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_sku_dimensions_api_sku_dimensions_lookup_get: {
        parameters: {
            query?: {
                /** @description FNSKU/SKU/EAN — repeat for batch */
                keys?: string[];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuDimensionLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_sku_dimensions_api_admin_sku_dimensions_get: {
        parameters: {
            query?: {
                /** @description Search FNSKU/SKU/EAN/Title */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paginated_SkuDimensionRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_sku_dimension_api_admin_sku_dimensions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkuDimensionUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuDimensionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_sku_dimension_api_admin_sku_dimensions__row_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_sku_dimension_api_admin_sku_dimensions__row_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkuDimensionUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuDimensionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_import_sku_dimensions_api_admin_sku_dimensions_import_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_admin_import_sku_dimensions_api_admin_sku_dimensions_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuDimensionImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_export_sku_dimensions_api_admin_sku_dimensions_export_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_auftraege_api_search_get: {
        parameters: {
            query: {
                /** @description FNSKU / SKU / EAN / Sendungsnummer / Dateiname */
                q: string;
                /** @description Untergrenze created_at (YYYY-MM-DD) */
                from?: string | null;
                /** @description Obergrenze created_at — inkl. 24h */
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_activity_live_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityFeed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_shift_api_activity_shift_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_auftraege_api_exports_auftraege_xlsx_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    spa_fallback__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
