"""audit_log auftrag_id on delete set null

Revision ID: 7ce58f95b176
Revises: d532b2666566
Create Date: 2026-05-02 09:55:43.007136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce58f95b176'
down_revision: Union[str, Sequence[str], None] = 'd532b2666566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_log_auftrag_id_fkey'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'audit_log', 'auftraege', ['auftrag_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('audit_log_auftrag_id_fkey'), 'audit_log', 'auftraege', ['auftrag_id'], ['id'])
    # ### end Alembic commands ###
