"""init schema

Revision ID: d532b2666566
Revises: 
Create Date: 2026-05-02 09:37:49.117941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd532b2666566'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auftraege',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('queued', 'in_progress', 'completed', 'error', name='auftrag_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('step', sa.Enum('pruefen', 'focus', 'abschluss', name='workflow_step'), nullable=True),
    sa.Column('current_pallet_idx', sa.Integer(), nullable=True),
    sa.Column('current_item_idx', sa.Integer(), nullable=True),
    sa.Column('completed_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('pallet_timings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auftraege_assigned', 'auftraege', ['assigned_to_user_id'], unique=False, postgresql_where=sa.text("status = 'in_progress'"))
    op.create_index('idx_auftraege_finished', 'auftraege', ['finished_at'], unique=False, postgresql_where=sa.text("status = 'completed'"))
    op.create_index('idx_auftraege_status', 'auftraege', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('auftrag_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftraege.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_user_created', 'audit_log', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_user_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_auftraege_status', table_name='auftraege')
    op.drop_index('idx_auftraege_finished', table_name='auftraege', postgresql_where=sa.text("status = 'completed'"))
    op.drop_index('idx_auftraege_assigned', table_name='auftraege', postgresql_where=sa.text("status = 'in_progress'"))
    op.drop_table('auftraege')
    op.drop_table('users')
    # ### end Alembic commands ###
